import { prisma, recordServiceHeartbeat } from '@prospector/database';
import { enqueueRun, prospectingQueue } from '@prospector/queues';
import { logger } from '@prospector/shared';
import { randomUUID } from 'crypto';
import { heartbeatCutoff, nextOccurrence, shouldRemoveQueuedJob } from './policy';

const log=logger('scheduler');let stopping=false;
async function dispatchSchedules(){const setting=await prisma.systemSetting.findUnique({where:{key:'automation'}});if((setting?.value as any)?.paused)return;const due=await prisma.schedule.findMany({where:{enabled:true,nextRunAt:{lte:new Date()}}});for(const schedule of due){await prisma.$transaction(async tx=>{const key=`schedule:${schedule.id}:${schedule.nextRunAt?.toISOString()??randomUUID()}`;const existing=await tx.prospectingRun.findUnique({where:{idempotencyKey:key}});if(existing)return;const run=await tx.prospectingRun.create({data:{scheduleId:schedule.id,country:schedule.country,state:schedule.state,city:schedule.city,category:schedule.category,idempotencyKey:key,status:'QUEUED',currentStage:'QUEUED'}});await tx.jobRecord.create({data:{queue:'prospecting',name:'prospect-run',runId:run.id,idempotencyKey:`prospecting:${run.id}`,payload:{runId:run.id}}});await tx.schedule.update({where:{id:schedule.id},data:{lastRunAt:new Date(),nextRunAt:nextOccurrence(schedule.scheduleType,schedule.nextRunAt??new Date()),enabled:schedule.scheduleType==='ONCE'?false:true}});await enqueueRun(run.id)})}}
async function recover(){const cutoff=heartbeatCutoff(new Date(),Number(process.env.HEARTBEAT_TIMEOUT_SECONDS??120));const stale=await prisma.prospectingRun.findMany({where:{status:'RUNNING',OR:[{heartbeatAt:{lt:cutoff}},{heartbeatAt:null}]}});for(const run of stale){await prisma.prospectingRun.update({where:{id:run.id},data:{status:'RECOVERING',currentStage:'RECOVERING'}});await prisma.jobRecord.updateMany({where:{runId:run.id},data:{state:'RECOVERING'}});await enqueueRun(run.id);log.warn({runId:run.id},'run recovered')}}
async function reconcile(){const queue=prospectingQueue();try{const durable=await prisma.prospectingRun.findMany({where:{status:{in:['PENDING','QUEUED','RECOVERING']}}});for(const run of durable){const job=await queue.getJob(`prospecting-${run.id}`);if(!job){const created=await queue.add('prospect-run',{runId:run.id},{jobId:`prospecting-${run.id}`,attempts:5,backoff:{type:'exponential',delay:2000}});await prisma.jobRecord.updateMany({where:{runId:run.id},data:{bullJobId:created.id,state:run.status==='RECOVERING'?'RECOVERING':'WAITING'}})}}const jobs=await queue.getJobs(['waiting','delayed']);for(const job of jobs){const runId=job.data?.runId;const run=runId?await prisma.prospectingRun.findUnique({where:{id:runId}}):null;if(shouldRemoveQueuedJob(run?.status))await job.remove()}}finally{await queue.close()}}
async function tick(){if(stopping)return;await recordServiceHeartbeat('scheduler').catch(()=>{});try{await dispatchSchedules();await recover();await recordServiceHeartbeat('recovery');await reconcile();await recordServiceHeartbeat('reconciliation')}catch(error:any){log.error({error:error.message},'scheduler tick failed')}}
async function main(){await tick();const timer=setInterval(tick,30000);async function shutdown(){stopping=true;clearInterval(timer);await prisma.$disconnect();process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);log.info('scheduler, recovery and reconciliation online')}
main().catch(error=>{log.fatal({error:error.message},'scheduler startup failed');process.exit(1)});
