import { prisma, recordServiceHeartbeat } from '@prospector/database';
import { campaignQueue, enqueueRun, prospectingQueue, websiteAnalysisQueue } from '@prospector/queues';
import { logger } from '@prospector/shared';
import { randomUUID } from 'crypto';
import { dispatchAutopilot } from './autopilot';
import { heartbeatCutoff, nextOccurrence } from './policy';
import { rebuildCampaignQueue, rebuildProspectingQueue, rebuildWebsiteAnalysisQueue, refreshStaleWebsiteAnalyses, syncQueuePauseState } from './reconciliation';

const log=logger('scheduler');const recoveryLog=logger('recovery');let stopping=false;
async function dispatchSchedules(){const setting=await prisma.systemSetting.findUnique({where:{key:'automation'}});if((setting?.value as any)?.paused)return;const due=await prisma.schedule.findMany({where:{enabled:true,nextRunAt:{lte:new Date()}}});for(const schedule of due){await prisma.$transaction(async tx=>{const key=`schedule:${schedule.id}:${schedule.nextRunAt?.toISOString()??randomUUID()}`;const existing=await tx.prospectingRun.findUnique({where:{idempotencyKey:key}});if(existing)return;const run=await tx.prospectingRun.create({data:{scheduleId:schedule.id,country:schedule.country,state:schedule.state,city:schedule.city,category:schedule.category,idempotencyKey:key,status:'QUEUED',currentStage:'QUEUED'}});await tx.jobRecord.create({data:{queue:'prospecting',name:'prospect-run',runId:run.id,idempotencyKey:`prospecting:${run.id}`,payload:{runId:run.id}}});await tx.schedule.update({where:{id:schedule.id},data:{lastRunAt:new Date(),nextRunAt:nextOccurrence(schedule.scheduleType,schedule.nextRunAt??new Date(),schedule.cronExpression,schedule.timezone),enabled:schedule.scheduleType==='ONCE'?false:true}});await enqueueRun(run.id);log.info({scheduleId:schedule.id,runId:run.id},'scheduled run dispatched')})}}
async function recover(){try{const cutoff=heartbeatCutoff(new Date(),Number(process.env.HEARTBEAT_TIMEOUT_SECONDS??120));const stale=await prisma.prospectingRun.findMany({where:{status:'RUNNING',OR:[{heartbeatAt:{lt:cutoff}},{heartbeatAt:null}]}});for(const run of stale){await prisma.prospectingRun.update({where:{id:run.id},data:{status:'RECOVERING',currentStage:'RECOVERING'}});await prisma.jobRecord.updateMany({where:{runId:run.id},data:{state:'RECOVERING'}});await enqueueRun(run.id);recoveryLog.warn({runId:run.id},'run recovered')}}catch(error:any){recoveryLog.error({error:error.message},'recovery cycle failed');throw error}}
async function reconcile(){const prospecting=prospectingQueue(),websites=websiteAnalysisQueue(),campaigns=campaignQueue();try{const setting=await prisma.systemSetting.findUnique({where:{key:'automation'}});await syncQueuePauseState([prospecting,websites,campaigns],Boolean((setting?.value as any)?.paused));const [runs,websiteResult,campaignsResult]=await Promise.all([rebuildProspectingQueue(prospecting),rebuildWebsiteAnalysisQueue(websites,new Date(),Number(process.env.HEARTBEAT_TIMEOUT_SECONDS??120)),rebuildCampaignQueue(campaigns,new Date(),Number(process.env.HEARTBEAT_TIMEOUT_SECONDS??120))]);const refreshResult=await refreshStaleWebsiteAnalyses(websites,new Date(),Number(process.env.WEBSITE_REFRESH_DAYS??30),Number(process.env.WEBSITE_REFRESH_BATCH_SIZE??20));await recordServiceHeartbeat('website-refresh').catch(()=>{});if(runs.rebuilt||runs.removed||websiteResult.rebuilt||campaignsResult.rebuilt||refreshResult.refreshed)log.warn({runs,websites:websiteResult,campaigns:campaignsResult,refresh:refreshResult},'redis queues rebuilt from PostgreSQL')}finally{await Promise.all([prospecting.close(),websites.close(),campaigns.close()])}}
async function tick(){if(stopping)return;await recordServiceHeartbeat('scheduler').catch(()=>{});try{await dispatchSchedules();const autopilotResult=await dispatchAutopilot();if(autopilotResult.dispatched)log.info({runId:autopilotResult.runId,targetId:autopilotResult.targetId},'autopilot run dispatched');await recover();await recordServiceHeartbeat('recovery');await reconcile();await recordServiceHeartbeat('reconciliation')}catch(error:any){log.error({error:error.message},'scheduler tick failed')}}
async function main(){await tick();const timer=setInterval(tick,30000);async function shutdown(){stopping=true;clearInterval(timer);log.info('scheduler stopping gracefully');await prisma.$disconnect();process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);log.info('scheduler and reconciliation online');recoveryLog.info('recovery service online')}
main().catch(error=>{log.fatal({error:error.message},'scheduler startup failed');process.exit(1)});
