import { BadRequestException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import ExcelJS from 'exceljs';
import { randomUUID } from 'crypto';
import { prisma } from '@prospector/database';
import { enqueueRun, prospectingQueue, campaignQueue } from '@prospector/queues';
import { heartbeatStatus } from '@prospector/shared';
import { businessFilterSchema, createRunSchema, createScheduleSchema } from '@prospector/validation';

@Injectable()
export class ApiService {
  async health(){let database='ONLINE',redis='ONLINE',heartbeats:any[]=[];try{await prisma.$queryRaw`SELECT 1`;heartbeats=await prisma.systemSetting.findMany({where:{key:{in:['service:worker','service:scheduler','service:recovery','service:reconciliation']}}})}catch{database='OFFLINE'};try{const q=prospectingQueue();await q.getJobCounts();await q.close()}catch{redis='OFFLINE'}const rows=Object.fromEntries(heartbeats.map(row=>[row.key,row.value]));const services={api:'ONLINE',database,redis,worker:heartbeatStatus(rows['service:worker'],45000),scheduler:heartbeatStatus(rows['service:scheduler'],90000),recovery:heartbeatStatus(rows['service:recovery'],90000),reconciliation:heartbeatStatus(rows['service:reconciliation'],90000)};return{status:Object.values(services).every(value=>value==='ONLINE')?'ok':'degraded',services,timestamp:new Date().toISOString()}}
  async login(body:any){const user=await prisma.user.findUnique({where:{email:String(body.email).toLowerCase()}});if(!user||!await bcrypt.compare(String(body.password),user.passwordHash))throw new UnauthorizedException('E-mail ou senha inválidos');return{token:jwt.sign({sub:user.id,email:user.email},process.env.JWT_SECRET??'change-me',{expiresIn:'12h'}),user:{name:user.name,email:user.email}}}
  async dashboard(){const [businesses,withWebsite,withPhone,whatsapp,high,runs,schedules,jobs,automation,health]=await Promise.all([prisma.business.count(),prisma.business.count({where:{website:{not:null}}}),prisma.business.count({where:{phone:{not:null}}}),prisma.businessPhone.count({where:{whatsappStatus:'AVAILABLE'}}),prisma.business.count({where:{leadScore:{gte:60}}}),prisma.prospectingRun.findMany({orderBy:{createdAt:'desc'},take:6}),prisma.schedule.findMany({where:{enabled:true,nextRunAt:{not:null}},orderBy:{nextRunAt:'asc'},take:5}),prisma.jobRecord.groupBy({by:['state'],_count:true}),prisma.systemSetting.findUnique({where:{key:'automation'}}),this.health()]);return{metrics:{businesses,withWebsite,withoutWebsite:businesses-withWebsite,withPhone,withoutPhone:businesses-withPhone,whatsapp,high},runs,schedules,jobs:Object.fromEntries(jobs.map(j=>[j.state,j._count])),services:health.services,healthCheckedAt:health.timestamp,settings:{dryRun:process.env.DRY_RUN!=='false',...(automation?.value as object??{})}}}
  runs(){return prisma.prospectingRun.findMany({orderBy:{createdAt:'desc'},take:100,include:{_count:{select:{cells:true,checkpoints:true}}}})}
  async createRun(raw:any){const parsed=createRunSchema.parse(raw);const {mode:_mode,...body}=parsed;const run=await prisma.prospectingRun.create({data:{...body,idempotencyKey:`manual:${randomUUID()}`}});await prisma.$transaction([prisma.jobRecord.create({data:{queue:'prospecting',name:'prospect-run',runId:run.id,idempotencyKey:`prospecting:${run.id}`,payload:{runId:run.id}}}),prisma.prospectingRun.update({where:{id:run.id},data:{status:'QUEUED',currentStage:'QUEUED'}})]);const job=await enqueueRun(run.id);await prisma.jobRecord.update({where:{idempotencyKey:`prospecting:${run.id}`},data:{bullJobId:job.id}});return run}
  async runAction(id:string,action:string){const run=await prisma.prospectingRun.findUnique({where:{id}});if(!run)throw new NotFoundException();if(action==='cancel')return prisma.prospectingRun.update({where:{id},data:{status:'CANCELLED',finishedAt:new Date()}});if(action==='retry'){await prisma.prospectingRun.update({where:{id},data:{status:'RECOVERING',errorMessage:null,finishedAt:null}});await enqueueRun(id);return{ok:true}};throw new BadRequestException('Ação inválida')}
  async businesses(raw:any){const q=businessFilterSchema.parse(raw);const where:any={};if(q.search)where.OR=[{name:{contains:q.search,mode:'insensitive'}},{address:{contains:q.search,mode:'insensitive'}}];if(q.city)where.city=q.city;if(q.state)where.state=q.state;if(q.category)where.category=q.category;if(q.siteStatus)where.siteStatus=q.siteStatus;if(q.minScore!=null)where.leadScore={gte:q.minScore};if(q.whatsapp==='true')where.phones={some:{whatsappStatus:'AVAILABLE'}};const [items,total]=await prisma.$transaction([prisma.business.findMany({where,include:{phones:true},orderBy:[{leadScore:'desc'},{updatedAt:'desc'}],skip:(q.page-1)*q.pageSize,take:q.pageSize}),prisma.business.count({where})]);return{items,total,page:q.page,pageSize:q.pageSize}}
  async business(id:string){const item=await prisma.business.findUnique({where:{id},include:{phones:true,snapshots:{orderBy:{capturedAt:'desc'},take:20},leadEvents:{orderBy:{createdAt:'desc'}}}});if(!item)throw new NotFoundException();return item}
  async leadStatus(id:string,body:any){const current=await prisma.business.findUnique({where:{id}});if(!current)throw new NotFoundException();return prisma.$transaction(async tx=>{const updated=await tx.business.update({where:{id},data:{leadStatus:body.status}});await tx.leadEvent.create({data:{businessId:id,fromStatus:current.leadStatus,toStatus:body.status,note:body.note}});if(body.status==='DO_NOT_CONTACT'&&current.normalizedPhone)await tx.contactSuppression.upsert({where:{normalizedPhone:current.normalizedPhone},update:{reason:body.note??'Opt-out'},create:{businessId:id,normalizedPhone:current.normalizedPhone,reason:body.note??'Opt-out'}});return updated})}
  schedules(){return prisma.schedule.findMany({orderBy:{createdAt:'desc'}})}
  createSchedule(raw:any){const body=createScheduleSchema.parse(raw);return prisma.schedule.create({data:body as any})}
  updateSchedule(id:string,body:any){return prisma.schedule.update({where:{id},data:body})}
  deleteSchedule(id:string){return prisma.schedule.delete({where:{id}})}
  jobs(){return prisma.jobRecord.findMany({orderBy:{createdAt:'desc'},take:200,include:{run:{select:{city:true,state:true,status:true}}}})}
  async jobAction(id:string,action:string){const job=await prisma.jobRecord.findUnique({where:{id}});if(!job)throw new NotFoundException();if(action==='retry'&&job.runId){await prisma.jobRecord.update({where:{id},data:{state:'RECOVERING',errorMessage:null}});await enqueueRun(job.runId);return{ok:true}}if(action==='cancel')return prisma.jobRecord.update({where:{id},data:{state:'CANCELLED'}});throw new BadRequestException('Ação inválida')}
  campaigns(){return prisma.campaign.findMany({orderBy:{createdAt:'desc'},include:{_count:{select:{messages:true}}}})}
  createCampaign(body:any){return prisma.campaign.create({data:{name:body.name,messageTemplate:body.messageTemplate,filters:body.filters??{},scheduledAt:body.scheduledAt?new Date(body.scheduledAt):null}})}
  async scheduleCampaign(id:string){const campaign=await prisma.campaign.findUnique({where:{id}});if(!campaign)throw new NotFoundException();const filters=campaign.filters as any;const businesses=await prisma.business.findMany({where:{phone:{not:null},leadScore:{gte:Number(filters.minScore??0)},city:filters.city||undefined,suppressions:{none:{}}}});await prisma.$transaction(businesses.map(b=>prisma.campaignMessage.upsert({where:{campaignId_businessId:{campaignId:id,businessId:b.id}},update:{},create:{campaignId:id,businessId:b.id,phone:b.normalizedPhone??b.phone!,idempotencyKey:`campaign:${id}:${b.id}`,scheduledAt:campaign.scheduledAt??new Date()}})));await prisma.campaign.update({where:{id},data:{status:'SCHEDULED'}});const q=campaignQueue();await q.add('send-campaign',{campaignId:id},{jobId:`campaign-${id}`,delay:Math.max(0,(campaign.scheduledAt?.getTime()??Date.now())-Date.now())});await q.close();return{selected:businesses.length}}
  async settings(){const row=await prisma.systemSetting.findUnique({where:{key:'automation'}});return{dryRun:process.env.DRY_RUN!=='false',autoSendCampaigns:process.env.AUTO_SEND_CAMPAIGNS==='true',automation:row?.value??{paused:false,autopilot:false}}}
  async emergency(action:string){if(!['stop','resume','autopilot-on','autopilot-off'].includes(action))throw new BadRequestException();const current=await prisma.systemSetting.findUnique({where:{key:'automation'}});const value:any=current?.value??{};if(action==='stop')value.paused=true;if(action==='resume')value.paused=false;if(action==='autopilot-on')value.autopilot=true;if(action==='autopilot-off')value.autopilot=false;await prisma.systemSetting.upsert({where:{key:'automation'},update:{value},create:{key:'automation',value}});const queues=[prospectingQueue(),campaignQueue()];for(const q of queues){action==='stop'?await q.pause():action==='resume'?await q.resume():null;await q.close()}return value}
  async exportCsv(){const rows=await prisma.business.findMany({include:{phones:true},orderBy:{name:'asc'}});const cols=['Empresa','Categoria','Endereço','Cidade','Estado','Telefone','WhatsApp','Site','Status Site','Rating','Avaliações','Google Maps','Lead Score','Data Descoberta','Última Atualização'];const escape=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;return '\uFEFF'+[cols,...rows.map(b=>[b.name,b.category,b.address,b.city,b.state,b.phone,b.phones[0]?.whatsappStatus,b.website,b.siteStatus,b.rating,b.reviewsCount,b.mapsUrl,b.leadScore,b.firstSeenAt.toISOString(),b.updatedAt.toISOString()])].map(r=>r.map(escape).join(';')).join('\n')}
  async exportXlsx(res:any){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Empresas');sheet.columns=['Empresa','Categoria','Endereço','Cidade','Estado','Telefone','WhatsApp','Site','Status Site','Rating','Avaliações','Google Maps','Lead Score','Data Descoberta','Última Atualização'].map(header=>({header,key:header,width:22}));const rows=await prisma.business.findMany({include:{phones:true}});rows.forEach(b=>sheet.addRow({'Empresa':b.name,'Categoria':b.category,'Endereço':b.address,'Cidade':b.city,'Estado':b.state,'Telefone':b.phone,'WhatsApp':b.phones[0]?.whatsappStatus,'Site':b.website,'Status Site':b.siteStatus,'Rating':b.rating,'Avaliações':b.reviewsCount,'Google Maps':b.mapsUrl,'Lead Score':b.leadScore,'Data Descoberta':b.firstSeenAt,'Última Atualização':b.updatedAt}));sheet.getRow(1).font={bold:true};res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="empresas.xlsx"');await workbook.xlsx.write(res);res.end()}
}
